### ISSUE TITLE
create 10 workspaces

### ISSUE THREAD

**Issue by AlphaTechnolog** [hluk/dwm#1]
I want to create a workspace named: `music`, but i need help to create it, it's are showed in the dwm bar, but it's not have a shortcut to access to it, my other workspaces, use the `MOD + N` shortcut (where `N` is equal than the index of the workspace. e.g: 'www -> MOD + 1', 'dev -> MOD + 2'), but i want to create a custom shorcut to it workspace (`MOD + 10`), the code for create the workspaces in my `config.h` is:

```c
static const char *tags[] = { "www", "dev", "term", "ref", "git", "docker", "fs", "vid", "misc", "music" }; // music is the 10 workspace
```

Help me please

**Comment by hluk** [comment]
This is just my personal git clone of dwm repo. I have not been using the window manager for a long time. Better to ask upstream.
